# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_no_Rasp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(708, 580)
        Dialog.setMinimumSize(QtCore.QSize(705, 580))
        Dialog.setMaximumSize(QtCore.QSize(710, 580))
        Dialog.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        self.ButtonPredict = QtWidgets.QPushButton(Dialog)
        self.ButtonPredict.setGeometry(QtCore.QRect(370, 410, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonPredict.setFont(font)
        self.ButtonPredict.setObjectName("ButtonPredict")
        self.lineFilePredict = QtWidgets.QLineEdit(Dialog)
        self.lineFilePredict.setGeometry(QtCore.QRect(480, 410, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineFilePredict.setFont(font)
        self.lineFilePredict.setObjectName("lineFilePredict")
        self.labelFilePredict = QtWidgets.QLabel(Dialog)
        self.labelFilePredict.setGeometry(QtCore.QRect(490, 370, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelFilePredict.setFont(font)
        self.labelFilePredict.setObjectName("labelFilePredict")
        self.labelSendArduino = QtWidgets.QLabel(Dialog)
        self.labelSendArduino.setGeometry(QtCore.QRect(120, 480, 481, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelSendArduino.setFont(font)
        self.labelSendArduino.setObjectName("labelSendArduino")
        self.btnSendData = QtWidgets.QPushButton(Dialog)
        self.btnSendData.setGeometry(QtCore.QRect(290, 520, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSendData.setFont(font)
        self.btnSendData.setDefault(False)
        self.btnSendData.setFlat(False)
        self.btnSendData.setObjectName("btnSendData")
        self.labelRecord = QtWidgets.QLabel(Dialog)
        self.labelRecord.setGeometry(QtCore.QRect(30, 370, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelRecord.setFont(font)
        self.labelRecord.setObjectName("labelRecord")
        self.btnStartRecord = QtWidgets.QPushButton(Dialog)
        self.btnStartRecord.setGeometry(QtCore.QRect(30, 410, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStartRecord.setFont(font)
        self.btnStartRecord.setAutoDefault(True)
        self.btnStartRecord.setFlat(False)
        self.btnStartRecord.setObjectName("btnStartRecord")
        self.labelStatus = QtWidgets.QLabel(Dialog)
        self.labelStatus.setGeometry(QtCore.QRect(140, 410, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelStatus.setFont(font)
        self.labelStatus.setObjectName("labelStatus")
        self.Image = QtWidgets.QLabel(Dialog)
        self.Image.setGeometry(QtCore.QRect(0, 0, 710, 360))
        self.Image.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("advantages-of-speech-recognition.jpg"))
        self.Image.setObjectName("Image")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Speech Recogition"))
        self.ButtonPredict.setText(_translate("Dialog", "PREDICT"))
        self.labelFilePredict.setText(_translate("Dialog", "COMMAND PREDICT"))
        self.labelSendArduino.setText(_translate("Dialog", "SEND DATA TO ARDUINO AND REMOTE THE CAR"))
        self.btnSendData.setText(_translate("Dialog", "SEND DATA"))
        self.labelRecord.setText(_translate("Dialog", "RECORDING"))
        self.btnStartRecord.setText(_translate("Dialog", "START"))
        self.labelStatus.setText(_translate("Dialog", "Nothing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
